Update sync-upstream.yml

diff --git a/.github/workflows/sync-upstream.yml b/.github/workflows/sync-upstream.yml
--- a/.github/workflows/sync-upstream.yml
+++ b/.github/workflows/sync-upstream.yml
@@ -1,29 +1,40 @@
-name: "Packages preview release"
+name: Upstream Sync
+
+permissions:
+  contents: write
+
 on:
-  push:
-    paths:
-      - "ui/packages/**"
-    branches:
-      - main
-  pull_request:
-    paths:
-      - "ui/packages/**"
-    branches:
-      - main
+  schedule:
+    - cron: "0 0 * * *" # every day
+  workflow_dispatch:
+
 jobs:
-  packages-preview-release:
+  sync_latest_from_upstream:
+    name: Sync latest commits from upstream repo
     runs-on: ubuntu-latest
-    if: github.repository == 'halo-dev/halo'
+    if: ${{ github.event.repository.fork }}
+
     steps:
-      - uses: actions/checkout@v4
-      - name: Setup Environment
-        uses: ./.github/actions/setup-env
+      # Step 1: run a standard checkout action
+      - name: Checkout target repo
+        uses: actions/checkout@v3
 
-      - name: Install Dependencies
-        run: ./gradlew pnpmInstall
+      # Step 2: run the sync action
+      - name: Sync upstream changes
+        id: sync
+        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
+        with:
+          upstream_sync_repo: halo-dev/halo
+          upstream_sync_branch: main
+          target_sync_branch: main
+          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, no need to set
 
-      - name: Build Packages
-        run: cd ui && pnpm build:packages
+          # Set test_mode true to run tests instead of the true action!!
+          test_mode: false
 
-      - name: Release
-        run: cd ui && pnpx pkg-pr-new publish --compact --pnpm './packages/*'
+      - name: Sync check
+        if: failure()
+        run: |
+          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次，详细教程请查看：https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README_CN.md#%E6%89%93%E5%BC%80%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0"
+          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the detailed tutorial for instructions: https://github.com/Yidadaa/ChatGPT-Next-Web#enable-automatic-updates"
+          exit 1
